# Use the official MySQL image from the Docker Hub
FROM mysql:8.0

# SHELL ["/bin/bash", "-c"]

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=6equj5_root
ENV MYSQL_USER=db_user
ENV MYSQL_DATABASE=home_db
ENV MYSQL_PASSWORD=6equj5_db_user

# RUN apt-get update && apt-get install -y python3 python3-pip

# COPY requirements.txt .

# RUN pip3 install -r ./requirements.txt

# Expose port 3306 for MySQL
EXPOSE 3307
