services: 
  mysql_ctn:
    build:
      context: .
      dockerfile: Dockerfile.initial_db
    container_name: mysql_ctn
    environment:
      MYSQL_ROOT_PASSWORD: 6equj5_root
      MYSQL_DATABASE: home_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 6equj5_db_user
    ports:
      - "3307:3306"
    volumes:
      - ./workspace:/var/lib/mysql:rw
      # - ./initdb:/docker-entrypoint-initdb.d 
    # networks:
    #   - app_net
    networks:
      - shared_net
      

# networks:
#   app_net:

# volumes:
#   mysql_vol:

networks:
  shared_net:
    external: true
    name: shared_network