# Use the official MySQL image from the Docker Hub
FROM mysql:8.0

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=6equj5_root
ENV MYSQL_USER=db_user
ENV MYSQL_DATABASE=home_db
ENV MYSQL_PASSWORD=6equj5_db_user

COPY ./sql/99_final_db_dump.sql /docker-entrypoint-initdb.d/

EXPOSE 3306
